### ISSUE TITLE
EAL: Error - exiting with code: 1   

### ISSUE THREAD

**Issue by Willendless** [stanford-mast/reflex#4]
Hi, when running relfex i got the error below
> EAL: Error - exiting with code: 1   
> Cause: No Ethernet ports - exiting  

however,  the Ethernet controller(82545EM Gigabit Ethernet Controller (Copper) 100f) has been bound to igb_uio and it's also ok when running examples in dpdk such as l2fwd

**Comment by hlitz** [comment]
Did you add the NIC in the cfg file? Should be described in the readme

**Comment by Willendless** [comment]
Thanks for reply, but in cfg file i have configured as   

> devices="0000:02:01.0"
> nvme_devices="0000:03:00.0"  

and after binding nic when using dpdk-devbind.py--status it shows as

> Network devices using DPDK-compatible driver
> 0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' drv=igb_uio   
> unused=uio_pci_generic  
> Network devices using kernel driver
> 0000:02:06.0 '82545EM Gigabit Ethernet Controller (Copper) 100f' if=ens38 drv=e1000 
> unused=igb_uio,uio_pci_generic *Active*

**Comment by anakli** [comment]
Your setup looks correct. However, I see you are using a different NIC than the ones we have tested ReFlex with, so the driver for this NIC is not included by default in the ReFlex `dp/Makefile`. You will need to add the necessary `.a` files to the DPDK_LIBS line in `dp/Makefile` and make sure to compile DPDK to include the driver for your NIC so those `.a` files are in the DPDK repo you are using for ReFlex. As an example, you can look at how this commit adds support for the Mellanox Connect X-5 NIC in the mlx5 branch of reflex: https://github.com/stanford-mast/reflex/commit/7a2e7ac39caf40c9e9df4f7e2f49349c79be5f17

**Comment by Willendless** [comment]
It works! Thanks a lot.
