### ISSUE TITLE
Client get stuck with high IOPS or large request size

### ISSUE THREAD

**Issue by yzygitzh** [stanford-mast/reflex#5]
Dear Authors,

Recently we came across your paper "ReFlex: Remote Flash ≈ Local Flash". It really does a good job, so we try to deploy ReFlex system in our testbed and reproduce some results in the paper. However, we encounter some issues running the ReFlex system.

We use two machines installed with Ubuntu 16.04, one as the client and another as the server, each with a Mellanox ConnectX-4 NIC. There are 3 switches between the two machines, i.e. 4 hops. We use `userspace` branch merged with `mlx5` branch.

**Firstly, we tried your open-loop example test command:**

`sudo ./dp/ix -s 10.1.2.39 -p 1234 -w seq -T 1 -i 500000 -r 100 -S 1 -R 1024 -P 0`

We changed the hard-coded target IOPS from 1K to 500K. In this scenario, client will stuck after a while. We pause client and server and check IP packets sent/received once client get stuck, and find that there are packets sent by server but never received by client, even with re-transmission by TCP.

**Secondly, we limit the queue size to 1 to test ping-pong latency with 4k request size:**

`sudo ./dp/ix -s 10.1.2.39 -p 1234 -w seq -T 1 -i 500000 -r 100 -S 1 -R 4096 -P 0`

In this scenario, client will stuck immediately after the first ever read request is sent to server. We pause the client and server and check IP packets sent/received, find that the first request is received, processed and sent back by server, but never received by client. If we change request size back to 1024 and keep the queue size limited to 1, everything is fine.

**Thirdly, we connect both machines directly by a cable, and everything is fine.**

Maybe these issues are already known to you. Could you help us with this? Thanks a lot!

**Comment by hlitz** [comment]
The packet loss issues have been fixed in the branch over here:
https://github.com/mhxie/reflex4arm
